export const MARKER = "<!-- generated by tenonry init; edits are overwritten -->";

export function renderTemplate(text, vars) {
  return text.replace(/\{\{\s*([A-Za-z0-9_]+)\s*\}\}/g, (_, name) => {
    if (!Object.hasOwn(vars, name) || vars[name] === undefined) throw new Error(`missing template variable: ${name}`);
    return String(vars[name]);
  });
}

export function bullets(list) {
  return list.map((item) => `- ${item}`).join("\n");
}

export function yamlList(list) {
  return list.map((item) => `  - ${item}`).join("\n");
}

export function numbered(list, prefix) {
  return list.map((item, index) => `${prefix}${index + 1}. ${item}`).join("\n");
}

export function hasMarker(text) {
  return text.trimEnd().split("\n").at(-1) === MARKER;
}

export function assertMarker(text, label) {
  if (!hasMarker(text)) throw new Error(`rendered text for ${label} does not end with the generated marker line`);
  if (text.split(MARKER).length !== 2) throw new Error(`rendered text for ${label} has more than one generated marker line`);
  return text;
}
